# Identificación del proyecto
sonar.projectKey=CNF_Respaldo_Transversal
sonar.projectName=Respaldo Transversal ACH

# Dónde está el código fuente
sonar.sources=src

# Dónde están las pruebas
sonar.test=test

# Exclusiones
sonar.exclusions=test/**, infra/**, **/mock_*.py

# Reporte de Cobertura
sonar.python.coverage.reportPaths=coverage.xml

# Endpoint de Sonar
# sonar.host.url=http://sonar.banistmo.com:9000